---
title: "Interpolation"
output: html_notebook
date: "2023-04-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- site_data_filtered_removedsites %>%
	group_by(soil_depth_min_cm, soil_depth_max_cm) %>%
	filter(TrtID == "E6_T13_CT_CR8",
				 year_name==2009)
	
depth_correction <- function(data,
														 accuracy = 0.125) # How many cm's per interpolated result
	{
	soc_data <- data %>%
	select(TrtID, year_name, soc_tha, soil_depth_max_cm, soil_depth_min_cm) %>%
	drop_na(soc_tha) %>%
	# Calculate midpoint and calculate the average soc per cm for each measurement depth
	mutate(midpoint = (soil_depth_min_cm + soil_depth_max_cm)/2,
				 guess = (soil_depth_max_cm - soil_depth_min_cm)/accuracy,
				 soc_tha_per_cm = soc_tha/(soil_depth_max_cm-soil_depth_min_cm),
				 soc_tha_per_cm_per_accuracy = soc_tha/(soil_depth_max_cm-soil_depth_min_cm)/(1/accuracy))

#Conduct interpolation
interp <- approx(x=soc_data$midpoint,
								 y=soc_data$soc_tha_per_cm_per_accuracy,
								 rule=2, # Adds floor and ceiling from lowest and highest y values
								 xout=seq(from = min(soc_data$soil_depth_min_cm),
								 				 to = max(soc_data$soil_depth_max_cm)-accuracy,
								 				 by = accuracy))

interp_data <- tibble(depth=interp$x, soc=interp$y)

return(sum(interp_data$soc))
}

```


Another approach:

``` {r}
minmax <- data %>%
	select(soil_depth_min_cm, soil_depth_max_cm) %>%
	group_split

minmax %>%
	purrr::map(function(x) {
		rezz <- ourdata %>%
			filter(depth >= x$soil_depth_min_cm &
						 	depth < x$soil_depth_max_cm)
		sn <- sum(rezz$soc)
		
		bizz <- sn/nrow(rezz)
		
		return(bizz)})

```

Graph:
```{r}
ggplot(data=tibble(x= interp$x, y=interp$y)) +
	geom_line(aes(x=x, y=y)) +
	geom_point(data=data, aes(x=midpoint, y=soc_tha_per_cm_per_accuracy)) +
	scale_x_continuous(limits = c(0, 30), breaks = seq(0, 30, 1)) +
	theme_bw() +
	ylab("SOC per cm per 1/accuracy") +
	xlab("cm")
```

```{r}
depth_correction(data)
```

The actual answer should be
```{r}
data %>%
	filter((soil_depth_min_cm == 0 & soil_depth_max_cm == 15) |
				 	(soil_depth_min_cm == 15 & soil_depth_max_cm == 30)) %>%
	pull(soc_tha) %>%
	sum
```
